version: "3.8"

services:
  web:
    build: .
    restart: always
    entrypoint: ["/app/entrypoint.sh"]
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/abide_slack_bot
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./.data:/app/.data
    networks:
      - abide-network

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=abide_slack_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - abide-network

networks:
  abide-network:
    driver: bridge

volumes:
  postgres_data:
